stages:
  - publish
  - deploy
publish:
  image: docker:latest
  stage: publish
  tags:
    - develop01
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERHUB_TOKEN
    - docker build -t ${APP_NAME} .
    - docker tag ${APP_NAME} $DOCKER_LOGIN/${APP_NAME}:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_LOGIN/${APP_NAME}:$CI_COMMIT_SHORT_SHA
deploy:
  stage: deploy
  tags:
    - develop01
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERHUB_TOKEN
    - docker pull $DOCKER_LOGIN/${APP_NAME}:$CI_COMMIT_SHORT_SHA
    - docker container rm -f docker-nginx || true
    - docker run -d -p 8081:80 --name docker-nginx $DOCKER_LOGIN/${APP_NAME}:$CI_COMMIT_SHORT_SHA
  only:
    - master
